services:
  - type: web
    name: sentinelx-gateway
    env: docker
    plan: free
    dockerfilePath: ./gateway/Dockerfile
    dockerContext: ./gateway
    envVars:
      - key: SENTINELX_ORIGIN_BASE_URL
        fromService:
          type: web
          name: origin-demo-service
          envVarKey: RENDER_EXTERNAL_URL
      - key: SENTINELX_ENVIRONMENT
        value: production
      - key: SENTINELX_REDIS_URL
        fromService:
          type: redis
          name: sentinelx-redis
          property: connectionString

  - type: web
    name: origin-demo-service
    env: docker
    plan: free
    dockerfilePath: ./demo-service/Dockerfile
    dockerContext: ./demo-service
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: origin-db
          property: connectionString

  - type: web
    name: sentinelx-orbit
    env: docker
    plan: free
    dockerfilePath: ./orbit/Dockerfile
    dockerContext: ./orbit
    envVars:
      - key: GATEWAY_URL
        fromService:
          type: web
          name: sentinelx-gateway
          envVarKey: RENDER_EXTERNAL_URL
      - key: ORBIT_ENV
        value: demo

  - type: web
    name: sentinelx-stub
    env: docker
    plan: free
    dockerfilePath: ./stub-service/Dockerfile
    dockerContext: ./stub-service

  - type: redis
    name: sentinelx-redis
    ipAllowList: []
    plan: free

databases:
  - name: origin-db
    databaseName: origin
    user: origin
    plan: free
